set_property IOSTANDARD LVCMOS33 [get_ports {status[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status[0]}]
set_property PACKAGE_PIN R2 [get_ports {status[1]}]
set_property PACKAGE_PIN T1 [get_ports {status[0]}]

set_property PACKAGE_PIN W7 [get_ports {display[7]}]
set_property PACKAGE_PIN W6 [get_ports {display[6]}]
set_property PACKAGE_PIN U8 [get_ports {display[5]}]
set_property PACKAGE_PIN V8 [get_ports {display[4]}]
set_property PACKAGE_PIN U5 [get_ports {display[3]}]
set_property PACKAGE_PIN V5 [get_ports {display[2]}]
set_property PACKAGE_PIN U7 [get_ports {display[1]}]
set_property PACKAGE_PIN V7 [get_ports {display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_addr[0]}]

set_property PACKAGE_PIN U2 [get_ports {dis_addr[0]}]
set_property PACKAGE_PIN U4 [get_ports {dis_addr[1]}]
set_property PACKAGE_PIN V4 [get_ports {dis_addr[2]}]
set_property PACKAGE_PIN W4 [get_ports {dis_addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_addr[2]}]

set_property PACKAGE_PIN V17 [get_ports CLR]
set_property IOSTANDARD LVCMOS33 [get_ports botton_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLR]
set_property PACKAGE_PIN T17 [get_ports botton_CLK]
set_property PACKAGE_PIN W5 [get_ports CLK]
